"""
CODE WITH ADAPTED FUNCTIONS FROM PMAGPY
"""

# ------------------------
# Import packages
import pmagpy.pmag as pmag
import pmagpy.pmagplotlib as pmagplotlib
import pmagpy.ipmag as ipmag
import pmagpy.contribution_builder as cb
from pmagpy import convert_2_magic as convert
import matplotlib.pyplot as plt 
import numpy as np        
import pandas as pd        
import os
from past.utils import old_div
import time
import math
import sys



def plot_di_mean(dec, inc, a95, label=None, circlabel=None, color='k', edge='k', marker='o', markersize=20, legend='no'):
    """
    Plot a mean direction (declination, inclination) with alpha_95 ellipse on
    an equal area plot.
    Before this function is called, a plot needs to be initialized with code
    that looks something like:
    >fignum = 1
    >plt.figure(num=fignum,figsize=(10,10),dpi=160)
    >ipmag.plot_net(fignum)
    Required Parameters
    -----------
    dec : declination of mean being plotted
    inc : inclination of mean being plotted
    a95 : a95 confidence ellipse of mean being plotted
    Optional Parameters (defaults are used if not specified)
    -----------
    color : the default color is black. Other colors can be chosen (e.g. 'r').
    marker : the default is a circle. Other symbols can be chosen (e.g. 's').
    markersize : the default is 20. Other sizes can be chosen.
    label : the default is no label. Labels can be assigned.
    legend : the default is no legend ('no'). Putting 'yes' will plot a legend.
    """
    DI_dimap = pmag.dimap(dec, inc)
    if inc < 0:
        plt.scatter(DI_dimap[0], DI_dimap[1],
                    edgecolors=edge, facecolors=color,
                    marker=marker, s=markersize, label=label)
    if inc >= 0:
        plt.scatter(DI_dimap[0], DI_dimap[1],
                    edgecolors=edge, facecolors=color,
                    marker=marker, s=markersize, label=label)
    Xcirc, Ycirc = [], []
    Da95, Ia95 = circ(dec, inc, a95)
    if legend == 'yes':
       plt.legend(loc=2)
    for k in range(len(Da95)):
        XY = pmag.dimap(Da95[k], Ia95[k])
        Xcirc.append(XY[0])
        Ycirc.append(XY[1])
    plt.plot(Xcirc, Ycirc, c=color, label=circlabel)
    plt.tight_layout()

    return DI_dimap,Xcirc,Ycirc

def plot_di_mean_ellipse(dictionary, fignum=1, color='k', edge='k', marker='o', markersize=20, label='', legend='no',line='yes'):
    """
    Plot a mean direction (declination, inclination)  confidence ellipse.
    Parameters
    -----------
    dictionary : a dictionary generated by the pmag.dobingham or pmag.dokent funcitons
    """
    pars = []
    pars.append(dictionary['dec'])
    pars.append(dictionary['inc'])
    pars.append(dictionary['Zeta'])
    pars.append(dictionary['Zdec'])
    pars.append(dictionary['Zinc'])
    pars.append(dictionary['Eta'])
    pars.append(dictionary['Edec'])
    pars.append(dictionary['Einc'])

    DI_dimap = pmag.dimap(dictionary['dec'], dictionary['inc'])
    if dictionary['inc'] < 0:
        plt.scatter(DI_dimap[0], DI_dimap[1],
                    edgecolors=edge, facecolors=color,
                    marker=marker, s=markersize, label=label)
    if dictionary['inc'] >= 0:
        plt.scatter(DI_dimap[0], DI_dimap[1],
                    edgecolors=edge, facecolors=color,
                    marker=marker, s=markersize, label=label)
    
    Xell, Yell = [], []  # declares map coordinates lists
    points=plot_ell(fignum, pars, color, 1, 0)  # calculate points forming ellipse (as dec, inc)
    for k in range(len(points)):
        dec_points,inc_points=points[k]         # store dec and inc of points in separate lists
        XY=pmag.dimap(dec_points,inc_points)    # convert dec and inc to map coordinates
        Xell.append(XY[0])                      # store coordinates in list
        Yell.append(XY[1])
        
    if line == 'yes': 
        plt.plot(Xell,Yell,c=color,label='Bootstrapped confidence ellipse')  # plot ellipse as line
    elif line == 'points':
        plot_ell(fignum, pars, color, 1, 1)     # plot ellipse as 200 points 
    if legend == 'yes':
        plt.legend(loc=2)       # plots legend
    
    return DI_dimap,Xell,Yell

def plot_ell(fignum, pars, col, lower, plot):
    """
    function to calcualte/plot points on an ellipse about Pdec,Pdip with angle beta,gamma
    Parameters
    _________
    fignum : matplotlib figure number
    pars : list of [Pdec, Pinc, beta, Bdec, Binc, gamma, Gdec, Ginc ]
         where P is direction, Bdec,Binc are beta direction, and Gdec,Ginc are gamma direction
    col : color for ellipse
    lower : boolean, if True, lower hemisphere projection
    plot : boolean, if False, return the points, if False, make the plot
    """
    #plt.figure(num=fignum)
    rad = old_div(np.pi, 180.)
    Pdec, Pinc, beta, Bdec, Binc, gamma, Gdec, Ginc = pars[0], pars[
        1], pars[2], pars[3], pars[4], pars[5], pars[6], pars[7]
    if beta > 90. or gamma > 90:
        beta = 180. - beta
        gamma = 180. - gamma
        Pdec = Pdec - 180.
        Pinc = -Pinc
    beta, gamma = beta * rad, gamma * rad  # convert to radians
    X_ell, Y_ell, X_up, Y_up, PTS = [], [], [], [], []
    nums = 201
    xnum = old_div(float(nums - 1.), 2.)
# set up t matrix
    t = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
    X = pmag.dir2cart((Pdec, Pinc, 1.0))  # convert to cartesian coordintes
    if lower == 1 and X[2] < 0:
        for i in range(3):
            X[i] = -X[i]
# set up rotation matrix t
    t[0][2] = X[0]
    t[1][2] = X[1]
    t[2][2] = X[2]
    X = pmag.dir2cart((Bdec, Binc, 1.0))
    if lower == 1 and X[2] < 0:
        for i in range(3):
            X[i] = -X[i]
    t[0][0] = X[0]
    t[1][0] = X[1]
    t[2][0] = X[2]
    X = pmag.dir2cart((Gdec, Ginc, 1.0))
    if lower == 1 and X[2] < 0:
        for i in range(3):
            X[i] = -X[i]
    t[0][1] = X[0]
    t[1][1] = X[1]
    t[2][1] = X[2]
# set up v matrix
    v = [0, 0, 0]
    for i in range(nums):  # incremental point along ellipse
        psi = float(i) * np.pi / xnum
        v[0] = np.sin(beta) * np.cos(psi)
        v[1] = np.sin(gamma) * np.sin(psi)
        v[2] = np.sqrt(1. - v[0]**2 - v[1]**2)
        elli = [0, 0, 0]
# calculate points on the ellipse
        for j in range(3):
            for k in range(3):
                # cartesian coordinate j of ellipse
                elli[j] = elli[j] + t[j][k] * v[k]
        pts = pmag.cart2dir(elli)
        PTS.append([pts[0], pts[1]])
        # put on an equal area projection
        R = old_div(np.sqrt(
            1. - abs(elli[2])), (np.sqrt(elli[0]**2 + elli[1]**2)))
        if elli[2] <= 0:
            #            for i in range(3): elli[i]=-elli[i]
            X_up.append(elli[1] * R)
            Y_up.append(elli[0] * R)
        else:
            X_ell.append(elli[1] * R)
            Y_ell.append(elli[0] * R)
    if plot == 1:
        col = col[0]+'.'
        if X_ell != []:
            plt.plot(X_ell, Y_ell, col, markersize=3)
        if X_up != []:
            plt.plot(X_up, Y_up, col, markersize=3)
    else:
        return PTS

def circ(dec, dip, alpha, n_points=201):
    """
    function to calculate points on an circle about dec,dip with angle alpha
    """
    rad = old_div(np.pi, 180.)
    D_out, I_out = [], []
    dec, dip, alpha = dec * rad, dip * rad, alpha * rad
    dec1 = dec + old_div(np.pi, 2.)
    isign = 1
    if dip != 0:
        isign = (old_div(abs(dip), dip))
    dip1 = (dip - isign * (old_div(np.pi, 2.)))
    t = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
    v = [0, 0, 0]
    t[0][2] = np.cos(dec) * np.cos(dip)
    t[1][2] = np.sin(dec) * np.cos(dip)
    t[2][2] = np.sin(dip)
    t[0][1] = np.cos(dec) * np.cos(dip1)
    t[1][1] = np.sin(dec) * np.cos(dip1)
    t[2][1] = np.sin(dip1)
    t[0][0] = np.cos(dec1)
    t[1][0] = np.sin(dec1)
    t[2][0] = 0
    for i in range(n_points):
        psi = float(i) * np.pi / ((n_points-1)/4)
        v[0] = np.sin(alpha) * np.cos(psi)
        v[1] = np.sin(alpha) * np.sin(psi)
        v[2] = np.sqrt(abs(1. - v[0]**2 - v[1]**2))
        elli = [0, 0, 0]
        for j in range(3):
            for k in range(3):
                elli[j] = elli[j] + t[j][k] * v[k]
        Dir = pmag.cart2dir(elli)
        D_out.append(Dir[0])
        I_out.append(Dir[1])
    return D_out, I_out

def in_ellipse(center,x_co,y_co,points,scatter='no'):
    """
    Determines if points is located inside ellipse (or circle).
    Parameters
    -----------
    center : list of x and y coordinate of center of ellipse (or circle)
    x_co   : list of x coordinates defining ellipse (or circle)
    y_co   : list of y coordinates defining ellipse (or circle)
    points  : nested list of x and y coordinates of points that will be tested'
    scatter : if 'yes', plots the input points red (if inside ellipse) or blue (outside ellipse)
    
    Return
    -----------
    location: list of 'in' or 'out' statements to indicate if point is inside ellipse

    """
    d=[]
    x_center,y_center=center[0],center[1]   # store x and y coordinate of center
    xs_out,ys_out,xs_in,ys_in=[],[],[],[]
        
    for k in range(len(points)):
        x_point,y_point=points[k][0],points[k][1]
        for i in range(len(x_co)):  # loop through number of ellipse points
         d_to_ellipse_point=np.sqrt((x_co[i]-x_point)**2+(y_co[i]-y_point)**2)    # calculate distance from point to ellipse point
         d.append(d_to_ellipse_point)   # store distances
        d_min=min(d)                    # distance of point to closest ellipse point
        indx=d.index(d_min)                 # get index of closest ellipse point
        x_ell,y_ell=x_co[indx],y_co[indx]   # get coordinates of closest ellipse point

        R1=np.sqrt((x_point-x_center)**2+(y_point-y_center)**2)     # calculate distance from point to center
        R2=np.sqrt((x_ell-x_center)**2+(y_ell-y_center)**2)         # calculate distance from ellipse point to center
        if R1>R2:       # check if point is outside ellipse
            xs_out.append(x_point)
            ys_out.append(y_point)
            location=0
        else:
            xs_in.append(x_point)
            ys_in.append(y_point)
            location=1
        d=[]    # empty list d
    
    if scatter=='yes':
        plt.scatter(xs_out,ys_out,c='blue',s=5)
        plt.scatter(xs_in,ys_in,c='red',s=5)

    return location

def plot_pole(dec=None, inc=None, di_block=None, color='k', marker='o', markersize=20, legend='no', label='', title='', edge='', alpha=1):
    """
    Plot declination, inclination data on an equal area plot.
    Before this function is called a plot needs to be initialized with code that looks
    something like:
    >fignum = 1
    >plt.figure(num=fignum,figsize=(10,10),dpi=160)
    >ipmag.plot_net(fignum)
    Required Parameters
    -----------
    dec : declination being plotted
    inc : inclination being plotted
    or
    di_block: a nested list of [dec,inc,1.0]
    (di_block can be provided instead of dec, inc in which case it will be used)
    Optional Parameters (defaults are used if not specified)
    -----------
    color : the default color is black. Other colors can be chosen (e.g. 'r')
    marker : the default marker is a circle ('o')
    markersize : default size is 20
    label : the default label is blank ('')
    legend : the default is no legend ('no'). Putting 'yes' will plot a legend.
    edge : marker edge color - if blank, is color of marker
    """
    X_down = []
    X_up = []
    Y_down = []
    Y_up = []
    color_down = []
    color_up = []

    if di_block is not None:
        di_lists = ipmag.unpack_di_block(di_block)
        if len(di_lists) == 3:
            dec, inc, intensity = di_lists
        if len(di_lists) == 2:
            dec, inc = di_lists
    try:
        length = len(dec)
        for n in range(len(dec)):
            XY = pmag.dimap(dec[n], inc[n])
            if inc[n] >= 0:
                X_down.append(XY[0])
                Y_down.append(XY[1])
                if type(color) == list:
                    color_down.append(color[n])
                else:
                    color_down.append(color)
            else:
                X_up.append(XY[0])
                Y_up.append(XY[1])
                if type(color) == list:
                    color_up.append(color[n])
                else:
                    color_up.append(color)
    except:
        XY = pmag.dimap(dec, inc)
        if inc >= 0:
            X_down.append(XY[0])
            Y_down.append(XY[1])
            color_down.append(color)
        else:
            X_up.append(XY[0])
            Y_up.append(XY[1])
            color_up.append(color)

    if len(X_up) > 0:
        plt.scatter(X_up, Y_up, facecolors=color_up, edgecolors=edge,
                    s=markersize, marker=marker, label=label, alpha=alpha)

    if len(X_down) > 0:
        plt.scatter(X_down, Y_down, facecolors=color_down, edgecolors=edge,
                    s=markersize, marker=marker, label=label, alpha=alpha)
    if legend == 'yes':
        plt.legend(loc=2)
    plt.tight_layout()
    if title != "":
        plt.title(title)

def docutoff(vgp_block,angle=45,di_block=0,plot=False):
    """
    Applies fixed cutoff to set of Virtual Geomagnetic Poles. Default is 45 degrees. 

    Parameters
    -----------
    vgp_block : a nested list of VGPs
    
    Optional Parameters (defaults are used if not specified)
    -----------
    angle : fixed cutoff angle from mean of VGPs
    di_block : a nested list of directions 
    plot : plots VGPs per iteration of cutoff procedure (red if rejected)

    Return
    -----------
    vgp_block : a nested list of VGPs after applying fixed angle cutoff
    vgp_block_rejected : a nested list of rejected VGPs
    di_block : a nested list of accepted directions (if di_block is specified)
    di_block_rejected : a nested list of rejected directions (if di_block is specified)
    """

    vgp_block_rejected=[]
    di_block_rejected=[]

    while True:
        vgp_mean = pmag.fisher_mean(vgp_block)  # calculate Fisher (1953) mean of VGPs
        ref_mean=[vgp_mean['dec'],vgp_mean['inc']]  # store mean longitude and latitude

        cutoffangle=angle   # store fixed cutoff angle, default is 45 degrees
        for i in range(len(vgp_block)): # loop through all VGPs
            angletomean=pmag.angle(vgp_block[i],ref_mean)   # calculate angle between VGP and mean
            if angletomean > cutoffangle:   # check if angle exceeds cutoff angle
                cutoffangle=angletomean     # store maximum angle 
                index=i                     # store index of VGP with maximum angle

        if cutoffangle==angle:  # if no angle exceeds cutoff angle, end algorithm
            break

        vgp_block_rejected.append(vgp_block[index]) # add rejected VGP to list
        vgp_block=np.delete(vgp_block,index,axis=0)
        #del vgp_block[index] # remove rejected VGP from original list of VGPs

        di_block_rejected.append(di_block[index]) # add rejected direction to list
        di_block=np.delete(di_block,index,axis=0)
        #del di_block[index] # remove rejected VGP from original list of directions
            

    # Plotting
    if plot==True:
        fignum = 1
        ipmag.plot_net(fignum)   # plot equal area projection
        ipmag.plot_di(di_block=di_block,color='darkgreen',edge='black',marker='o',markersize=40,label='accepted')
        ipmag.plot_di(di_block=di_block_rejected,color='red',edge='black',marker='o',markersize=40,label='rejected')
        ipmag.plot_di_mean(dec=vgp_mean['dec'],inc=vgp_mean['inc'],a95=angle,color='black',marker='*',markersize=100,label='mean of accepted VGPs')
        plt.legend(loc=1,fontsize='large')
        plt.show()

    return vgp_block,vgp_block_rejected,di_block,di_block_rejected

def donewvandamme(vgp_block,di_block=0,plot=False):
    """
    Applies the Vandamme (1994) to set of Virtual Geomagnetic Poles. Follows recursive method of figure 5 of original publication.

    Parameters
    -----------
    vgp_block : a nested list of VGPs
    
    Optional Parameters (defaults are used if not specified)
    -----------
    plot : plots VGPs per iteration of cutoff procedure (red if rejected)
    di_block : a nested list of directions 

    Return
    -----------
    vgp_block : a nested list of VGPs after applying fixed angle cutoff
    vgp_block_rejected : a nested list of rejected VGPs
    ASD : angular standard deviation after cutoff
    A : cutoff angle
    di_block : a nested list of accepted directions (if di_block is specified)
    di_block_rejected : a nested list of rejected directions (if di_block is specified)
    """
    
    vgp_block_rejected=[]
    di_block_rejected=[]
    
    while True:
        vgp_mean = pmag.fisher_mean(vgp_block)  # calculate Fisher (1953) mean of VGPs
        ref_mean=[vgp_mean['dec'],vgp_mean['inc']]  # store mean longitude and latitude

        maxangle=0
        deltasum=0
        N=len(vgp_block)
        for i in range(N): # loop through all VGPs
            angletomean=pmag.angle(vgp_block[i],ref_mean)   # calculate angle between VGP and mean
            if angletomean[0] > maxangle:   # check if angle exceeds largest angle
                maxangle=angletomean[0]     # store maximum angle 
                index=i                        # store index of VGP with maximum angle
            deltasum+=math.pow(angletomean[0],2) # add angle to sum of squared angles

        # Apply method of Vandamme (1994)
        ASD=math.sqrt(deltasum/(N-1)) # calculate angular standard deviation
        A=1.8 * ASD + 5. # calculate optimum cutoff angle (A)

        if maxangle<A:  # if largest angle does not exceed optimum cutoff angle, end algorithm
            break

        vgp_block_rejected.append(vgp_block[index]) # add rejected VGP to list
        vgp_block=np.delete(vgp_block,index,axis=0)
        #del vgp_block[index] # remove rejected VGP from original list of VGPs

        di_block_rejected.append(di_block[index]) # add rejected direction to list
        di_block=np.delete(di_block,index,axis=0)

        # Plotting
        if plot==True:
            fignum = 1
            ipmag.plot_net(fignum)   # plot equal area projection
            ipmag.plot_di(di_block=vgp_block,color='darkgreen',edge='black',marker='o',markersize=40,label='accepted')
            ipmag.plot_di(di_block=vgp_block_rejected,color='red',edge='black',marker='o',markersize=40,label='rejected')
            plot_di_mean(dec=vgp_mean['dec'],inc=vgp_mean['inc'],a95=A,color='black',edge='black',marker='*',markersize=100,label='mean of accepted VGPs')
            plt.legend(loc=1,fontsize='large')
            plt.show()
            
    print('ASD = %1.1f' % ASD)
    print('Cutoff angle = %1.1f' % A)

    return vgp_block,vgp_block_rejected,di_block,di_block_rejected

def di2vgp(di_block,slat=0,slon=0,samp_loc=0):
    """
    Converts directional data (declination, inclination) at a given sampling
    location (Site latitude, Site longitude) to pole position (pole longitude,
    pole latitude)

    Required Parameters
    -----------
    di_block : nested list of direction given as [declination,inclination] 
    slat : sampling latitude
    slon : sampling longitude
    samp_loc : sampling location(s) given as nested list of [site LATITUDE, site LONGITUDE]

    Return
    -----------
    plat : latitude of VGP (or pole) associates with paleomagnetic direction assuming a GAD field
    plon : longitude of VGP (or pole) associates with paleomagnetic direction assuming a GAD field
    """
    # check number of directions
    n_dirs = len(di_block)

    # check if there are multiple sampling locations
    if samp_loc==0:

        input_list=[[di_block[k][0],di_block[k][1],0,slat,slon] for k in range(n_dirs)]
        output_list=pmag.dia_vgp(input_list)
        vgp_block=[[output_list[0][k],output_list[1][k]] for k in range(n_dirs)]

    else:
        n_locs = len(samp_loc)

        if n_dirs!=n_locs:
            print('ERROR: NUMBER OF LOCATIONS ARE NOT EQUAL TO NUMBER OF DIRECTIONS')
        else:
            input_list=[[di_block[k][0],di_block[k][1],0,samp_loc[k][0],samp_loc[k][1]] for k in range(n_dirs)]
            output_list=pmag.dia_vgp(input_list)
            vgp_block=[[output_list[0][k],output_list[1][k]] for k in range(n_dirs)]

    return vgp_block


def find_ei(data, nb=1000, save=False, save_folder='.', fmt='svg',
            site_correction=False, return_new_dirs=False, params=False):
    """
    Applies series of assumed flattening factor and "unsquishes" inclinations assuming tangent function.
    Finds flattening factor that gives elongation/inclination pair consistent with TK03;
    or, if correcting by site instead of for study-level secular variation,
    finds flattening factor that minimizes elongation and most resembles a
    Fisherian distribution.
    Finds bootstrap confidence bounds
    Required Parameter
    -----------
    data: a nested list of dec/inc pairs
    Optional Parameters (defaults are used unless specified)
    -----------
    nb: number of bootstrapped pseudo-samples (default is 1000)
    save: Boolean argument to save plots (default is False)
    save_folder: path to folder in which plots should be saved (default is current directory)
    fmt: specify format of saved plots (default is 'svg')
    site_correction: Boolean argument to specify whether to "unsquish" data to
        1) the elongation/inclination pair consistent with TK03 secular variation model
        (site_correction = False)
        or
        2) a Fisherian distribution (site_correction = True). Default is FALSE.
        Note that many directions (~ 100) are needed for this correction to be reliable.
    return_new_dirs: optional return of newly "unflattened" directions (default is False)
    Returns
    -----------
    four plots:   1) equal area plot of original directions
                  2) Elongation/inclination pairs as a function of f,  data plus 25 bootstrap samples
                  3) Cumulative distribution of bootstrapped optimal inclinations plus uncertainties.
                     Estimate from original data set plotted as solid line
                  4) Orientation of principle direction through unflattening
    NOTE: If distribution does not have a solution, plot labeled: Pathological.  Some bootstrap samples may have
       valid solutions and those are plotted in the CDFs and E/I plot.
    """
    print("Bootstrapping.... be patient")
    print("")
    sys.stdout.flush()

    upper, lower = int(round(.975 * nb)), int(round(.025 * nb))
    E, I = [], []

    plt.figure(num=1, figsize=(4.5, 4.5))
    ipmag.plot_net(1)
    ipmag.plot_di(di_block=data)
    plt.title('Original')
    ppars = pmag.doprinc(data)
    Io = ppars['inc']
    n = ppars["N"]
    Es, Is, Fs, V2s = pmag.find_f(data)
    if site_correction == True:
        Inc, Elong = Is[Es.index(min(Es))], Es[Es.index(min(Es))]
        flat_f = Fs[Es.index(min(Es))]
    else:
        Inc, Elong = Is[-1], Es[-1]
        flat_f = Fs[-1]

    if (Inc, Elong, flat_f) == (0, 0, 0):
        print("NO INTERSECTION WITH E/I CURVE")
    else:
        plt.figure(num=2, figsize=(4.5,4.5))
        plt.plot(Is, Es, 'r')
        plt.xlabel("Inclination")
        plt.ylabel("Elongation")
        plt.text(Inc, Elong, ' %3.2f' % (flat_f))
        plt.text(Is[0] - 2, Es[0], ' %s' % ('f=1'))

        b = 0

        while b < nb:
            bdata = pmag.pseudo(data)
            Esb, Isb, Fsb, V2sb = pmag.find_f(bdata)
            if b < 25:
                plt.plot(Isb, Esb, 'y')
            if Esb[-1] != 0:
                ppars = pmag.doprinc(bdata)
                if site_correction == True:
                    I.append(abs(Isb[Esb.index(min(Esb))]))
                    E.append(Esb[Esb.index(min(Esb))])
                else:
                    I.append(abs(Isb[-1]))
                    E.append(Esb[-1])
                b += 1

        I.sort()
        E.sort()
        Eexp = []
        for i in I:
            Eexp.append(pmag.EI(i))
        plt.plot(I, Eexp, 'g-')
        if Inc == 0:
            title = 'Pathological Distribution: ' + \
                '[%7.1f, %7.1f]' % (I[lower], I[upper])
        else:
            title = '%7.1f [%7.1f, %7.1f]' % (Inc, I[lower], I[upper])
        #plt.savefig(fname='ei2.pdf',dpi='figure',format='pdf')

        cdf_fig_num = 3
        plt.figure(num=cdf_fig_num, figsize=(4.5,4.5))
        pmagplotlib.plot_cdf(cdf_fig_num, I, 'Inclinations', 'r', title)
        pmagplotlib.plot_vs(cdf_fig_num, [I[lower], I[upper]], 'b', '--')
        pmagplotlib.plot_vs(cdf_fig_num, [Inc], 'g', '-')
        pmagplotlib.plot_vs(cdf_fig_num, [Io], 'k', '-')
        #plt.savefig(fname='ei3.pdf',dpi='figure',format='pdf')

    # plot corrected directional data

    di_lists = ipmag.unpack_di_block(data)
    if len(di_lists) == 3:
        decs, incs, intensity = di_lists
    if len(di_lists) == 2:
        decs, incs = di_lists
    if flat_f:
        unsquished_incs = ipmag.unsquish(incs, flat_f)
        plt.figure(num=4, figsize=(4, 4))
        ipmag.plot_net(4)
        ipmag.plot_di(decs, unsquished_incs)
        plt.title('Corrected for flattening')
    else:
        plt.figure(num=4, figsize=(4, 4))
        ipmag.plot_net(4)
        ipmag.plot_di(decs, incs)
        plt.title('Corrected for flattening')

    if (Inc, Elong, flat_f) == (0, 0, 0):
        print("PATHOLOGICAL DISTRIBUTION")
    else:
        print("The original inclination was: " + str(Io))
        print("")
        print("The corrected inclination is: " + str(Inc))
        print("with bootstrapped confidence bounds of: " +
            str(I[lower]) + ' to ' + str(I[upper]))
        print("and elongation parameter of: " + str(Elong))
        print("The flattening factor is: " + str(flat_f))

    if return_new_dirs is True:
        if (Inc, Elong, flat_f) == (0, 0, 0):
            inc_list = [0] * len(decs)
            return ipmag.make_di_block(decs, inc_list)
        else:
            if params is False:
                return ipmag.make_di_block(decs, unsquished_incs)
            else:
                return ipmag.make_di_block(decs, unsquished_incs),flat_f,I[lower],I[upper]